#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# Setting layou
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Set padding 
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

# setting all windows same space
yabai -m config auto_balance off
yabai -m config split_ratio 0.5

# set mouse interaction modifier key 
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus on


# yabai -m config window_shadow float
# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 0.5
# yabai -m config normal_window_opacity 0.1
#
# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Simulator$" manage=off

yabai -m config external_bar main:35:0
# yabai -m config external_bar all:20:20
#
yabai -m space 1 --create 
yabai -m space 2 --create
yabai -m space 3 --create
yabai -m space 4 --create
yabai -m space 5 --create
yabai -m space 6 --create
yabai -m space 7 --create
yabai -m space 8 --create

echo "yabai configuration loaded.."
