#!/usr/bin/env sh
#
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space $idx --create
  fi

  yabai -m space "$idx" --label "$name"
}


sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# Setting layou
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Set padding 
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

# setting all windows same space
yabai -m config auto_balance off
yabai -m config split_ratio 0.5

# set mouse interaction modifier key 
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus on


# yabai -m config window_shadow float
# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
# yabai -m config active_window_opacity 0.95
# yabai -m config normal_window_opacity 0.8
#
# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^scrcpy$" manage=off
# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off


# yabai -m config external_bar main:35:0
# yabai -m config external_bar all:20:20
#
# yabai -m space 1 --create 
# yabai -m space 2 --create
# yabai -m space 3 --create
# yabai -m space 4 --create
# yabai -m space 5 --create
# yabai -m space 6 --create
# yabai -m space 7 --create
# yabai -m space 8 --create
#
setup_space 1 dev
setup_space 2 web
setup_space 3 chat
setup_space 4 music
setup_space 5 vms

APP_LIST="(Spotify|Music|WezTerm|wezterm-gui)"
yabai -m signal --add event=window_focused app="^${APP_LIST}$" action="yabai -m config active_window_opacity 0.90"
yabai -m signal --add event=window_focused app="^${APP_LIST}$" action="yabai -m config normal_window_opacity 1.0"

yabai -m signal --add event=window_focused app!="^${APP_LIST}$" action="yabai -m config active_window_opacity 1.0"
yabai -m signal --add event=window_focused app!="^${APP_LIST}$" action="yabai -m config normal_window_opacity 1.0"
#
yabai -m rule --add app="^Docker$" space=vms
yabai -m rule --add app="^Spotify$" space=music
yabai -m rule --add app="^Music$" space=music
yabai -m rule --add app="^wezterm-gui$" space=code
# yabai -m rule --add app="^WezTerm$" space=code
yabai -m rule --add app="^WhatsApp$" space=chat
yabai -m rule --add app="^Mail$" space=chat

echo "yabai configuration loaded.."
